name: PagePilot
options:
  bundleIdPrefix: org.readium
  schemePathPrefix: ../../../
fileGroups:
  - PagePilot.storekit
schemes:
  PagePilot:
    build:
      targets:
        PagePilot: all
    run:
      storeKitConfiguration: PagePilot.storekit
targets:
  PagePilot:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: iPhone
      - path: Sources
        excludes:
          - Resources/Fonts
      - path: Sources/Resources/Fonts
        type: folder
      - path: Shared
    dependencies:
      - target: PagePilotWatch
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.panyang.PagePilot
      DEVELOPMENT_TEAM: ${RD_DEVELOPMENT_TEAM}

  PagePilotWatch:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: WatchRemote
      - path: Shared
    settings:
      INFOPLIST_FILE: WatchRemote/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.panyang.PagePilot.WatchRemote
      DEVELOPMENT_TEAM: ${RD_DEVELOPMENT_TEAM}
